[tool.poetry]
name = "volttron-listener"
version = "2.0.0rc4"
description = "The volttron-listener agent allows publishing of message bus traffic to standard out."
authors = [
    "VOLTTRON Team <volttron@pnnl.gov>",
]
license = "Apache License 2.0"
readme = "README.md"
repository = "https://github.com/eclipse-volttron/volttron-listener"
homepage = "https://github.com/eclipse-volttron/volttron-listener"
keywords = []
include =[{path="volttron-listener-default-vip-id", format = ["sdist", "wheel"]}]
packages = [
    { include = "listener", from = "src" },
]
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Developers",
    "Intended Audience :: Other Audience",
    "License :: OSI Approved :: Apache Software License",
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
volttron-core = ">=2.0.0rc13"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
#volttron-testing = {path = "../volttron-testing", develop = true}
#volttron-core = {path = "../volttron-core", develop = true}


[tool.poetry.scripts]
volttron-listener-agent = "listener.agent:main"


[tool.yapfignore]
ignore_patterns = [
    ".venv/**",
    ".pytest_cache/**",
    "dist/**",
    "docs/**",
]

[tool.yapf]
based_on_style = "pep8"
spaces_before_comment = 4
column_limit = 120
split_before_logical_operator = true

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
